### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by pacospace** [thoth-station/mi#187] opened 2020-08-21 09:27 UTC
**Describe the bug**
`TypeError: '<' not supported between instances of 'NoneType' and 'str'` encountered in many mi-analysis workflows in thoth-test-core.

**Expected behavior**
MI-analysis run successfully.

**Screenshots**
```
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Saving knowledge file process_issues_closed_by_pr_size.json of size 0
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Saved on CEPH at thoth/data/srcopsmetrics/processed/AICoE/ludus/process_issues_closed_by_pr_size.json
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Loading knowledge from Ceph
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Found previous knowledge for None with 2 entities of type Processed Knowledge
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Loading knowledge from Ceph
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:No previous knowledge of type Processed Knowledge found
mi-analysis-mi-55f22b4b-587114087: INFO:srcopsmetrics.storage:Saving knowledge file process_issue_labels_to_issue_closers.json of size 5
mi-analysis-mi-55f22b4b-587114087: Traceback (most recent call last):
mi-analysis-mi-55f22b4b-587114087:   File "srcopsmetrics/cli.py", line 134, in <module>
mi-analysis-mi-55f22b4b-587114087:     cli()
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
mi-analysis-mi-55f22b4b-587114087:     return self.main(*args, **kwargs)
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
mi-analysis-mi-55f22b4b-587114087:     rv = self.invoke(ctx)
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
mi-analysis-mi-55f22b4b-587114087:     return ctx.invoke(self.callback, **ctx.params)
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
mi-analysis-mi-55f22b4b-587114087:     return callback(*args, **kwargs)
mi-analysis-mi-55f22b4b-587114087:   File "srcopsmetrics/cli.py", line 117, in cli
mi-analysis-mi-55f22b4b-587114087:     Processing(issues=issues, pull_requests=prs).regenerate()
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/src/srcopsmetrics/processing.py", line 56, in regenerate
mi-analysis-mi-55f22b4b-587114087:     self.process_issue_labels_to_issue_closers()
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/src/srcopsmetrics/storage.py", line 72, in __call__
mi-analysis-mi-55f22b4b-587114087:     storage.save_knowledge(file_path=total_path, data=knowledge)
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/src/srcopsmetrics/storage.py", line 120, in save_knowledge
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 87, in store_document
mi-analysis-mi-55f22b4b-587114087:     s3.store_document(results, ceph_filename)
mi-analysis-mi-55f22b4b-587114087:     blob = self.dict2blob(document)
mi-analysis-mi-55f22b4b-587114087:   File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 73, in dict2blob
mi-analysis-mi-55f22b4b-587114087:     return json.dumps(dictionary, sort_keys=True, separators=(",", ": "), indent=2).encode()
mi-analysis-mi-55f22b4b-587114087:   File "/usr/lib64/python3.6/json/__init__.py", line 238, in dumps
mi-analysis-mi-55f22b4b-587114087:     **kw).encode(obj)
mi-analysis-mi-55f22b4b-587114087:   File "/usr/lib64/python3.6/json/encoder.py", line 201, in encode
mi-analysis-mi-55f22b4b-587114087:     chunks = list(chunks)
mi-analysis-mi-55f22b4b-587114087:   File "/usr/lib64/python3.6/json/encoder.py", line 430, in _iterencode
mi-analysis-mi-55f22b4b-587114087:   File "/usr/lib64/python3.6/json/encoder.py", line 404, in _iterencode_dict
mi-analysis-mi-55f22b4b-587114087:     yield from _iterencode_dict(o, _current_indent_level)
mi-analysis-mi-55f22b4b-587114087:     yield from chunks
mi-analysis-mi-55f22b4b-587114087:   File "/usr/lib64/python3.6/json/encoder.py", line 353, in _iterencode_dict
mi-analysis-mi-55f22b4b-587114087: TypeError: '<' not supported between instances of 'NoneType' and 'str'
mi-analysis-mi-55f22b4b-587114087:     items = sorted(dct.items(), key=lambda kv: kv[0])
```

**Comment by xtuchyna** [comment] 2020-10-14 13:24
The processing not used currently  (because of the removed visualizations).
Therefore the matter of the issue is not relevant anymore -> closing it

**Closed by xtuchyna** 2020-10-14 13:24 UTC
